----------------------------------------------------------------------------------------------------------------
--  Exercice 3 : création d'une procédure stockée avec plusieurs paramètres  --
--  Créer la procédure stockée CA_Supplier, qui pour un code fournisseur et une année entrée en paramètre, calcule et restitue le CA potentiel de ce fournisseur pour l'année souhaitée.  --
----------------------------------------------------------------------------------------------------------------